CREATE TABLE public.ORDERS
(
   ORDER_ID SERIAL PRIMARY KEY NOT NULL,
   ORDER_NAME CHAR(50),    		
   ORDER_ADDDATE DATE DEFAULT CURRENT_DATE,
   USER_ID INTEGER, 
   FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);
