package com.company.webapp.util;

public enum SQLQuery {
    //======USERS SQL=========
    USER_SELECT_ALL("SELECT * FROM USERS;"),
    USER_DELETE("DELETE FROM USERS WHERE ID =?;"),
    USER_INSERT("INSERT INTO USERS(NAME,SNAME,PATR,BDATE) VALUES (?,?,?,?);"),
    USER_UPDATE("UPDATE USERS SET (NAME,SNAME,PATR,BDATE) = (?,?,?,?) WHERE ID = ?;"),
    USER_SELECT_ONE("SELECT * FROM USERS WHERE ID = ?;"),
    USER_SELECT_IF_EXISTS("SELECT * FROM USERS WHERE EXIST = TRUE;"),
    USER_SET_NOT_EXIST("UPDATE USERS SET EXIST = FALSE WHERE ID = ?;"),
    USER_GET_COUNT("SELECT COUNT(ID) FROM USERS;"),

    //======ORDERS SQL=========
    ORDER_SELECT_ALL("SELECT * FROM ORDERS;"),
    ORDER_DELETE("DELETE FROM ORDERS WHERE ID =?;"),
    ORDER_DELETE_BY_USER_ID("DELETE FROM ORDERS WHERE USER_ID = ?;"),
    ORDER_INSERT("INSERT INTO ORDERS(NAME,ADDDATE,USER_ID) VALUES (?,?,?);"),
    ORDER_UPDATE("UPDATE ORDERS SET (NAME) = (?) WHERE ID = ?;"),
    ORDER_SELECT_ONE("SELECT * FROM ORDERS WHERE ID = ?;"),
    ORDER_SELECT_BY_USER("SELECT * FROM ORDERS WHERE USER_ID = ? "),
    ORDER_GET_COUNT_BY_USER("SELECT COUNT(ID) FROM ORDERS WHERE USER_ID=?;"),
    ORDER_GET_COUNT("SELECT COUNT(ID) FROM ORDERS;");
    //=======================

    private String query;

    SQLQuery(String query) {
        this.query = query;
    }

    public String getQuery() {
        return query;
    }
}